/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author Lenovo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuConsulta = new javax.swing.JMenu();
        MenuItemNacionales = new javax.swing.JMenuItem();
        MenuItemInternacionales = new javax.swing.JMenuItem();
        MenuItemTransOceanicos = new javax.swing.JMenuItem();
        MenuEditar = new javax.swing.JMenu();
        MenuItemAgregar = new javax.swing.JMenuItem();
        MenuItemModificar = new javax.swing.JMenuItem();
        MenuItemEliminar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        MenuConsulta.setText("Consultar Vuelos");

        MenuItemNacionales.setText("Nacionales");
        MenuItemNacionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemNacionalesActionPerformed(evt);
            }
        });
        MenuConsulta.add(MenuItemNacionales);

        MenuItemInternacionales.setText("Internacionales");
        MenuConsulta.add(MenuItemInternacionales);

        MenuItemTransOceanicos.setText("TransOceanicos");
        MenuConsulta.add(MenuItemTransOceanicos);

        MenuPrincipal.add(MenuConsulta);

        MenuEditar.setText("Editar Vuelos");

        MenuItemAgregar.setText("Agregar Vuelo");
        MenuItemAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAgregarActionPerformed(evt);
            }
        });
        MenuEditar.add(MenuItemAgregar);

        MenuItemModificar.setText("Modificar Vuelo");
        MenuEditar.add(MenuItemModificar);

        MenuItemEliminar.setText("Eliminar Vuelo");
        MenuEditar.add(MenuItemEliminar);

        MenuPrincipal.add(MenuEditar);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemAgregarActionPerformed

    private void MenuItemNacionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemNacionalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemNacionalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    public JDesktopPane getEscritorio() {
        return Escritorio;
    }

    public void setEscritorio(JDesktopPane Escritorio) {
        this.Escritorio = Escritorio;
    }

    public JMenu getMenuConsulta() {
        return MenuConsulta;
    }

    public void setMenuConsulta(JMenu MenuConsulta) {
        this.MenuConsulta = MenuConsulta;
    }

    public JMenu getMenuEditar() {
        return MenuEditar;
    }

    public void setMenuEditar(JMenu MenuEditar) {
        this.MenuEditar = MenuEditar;
    }

    public JMenuItem getMenuItemAgregar() {
        return MenuItemAgregar;
    }

    public void setMenuItemAgregar(JMenuItem MenuItemAgregar) {
        this.MenuItemAgregar = MenuItemAgregar;
    }

    public JMenuItem getMenuItemEliminar() {
        return MenuItemEliminar;
    }

    public void setMenuItemEliminar(JMenuItem MenuItemEliminar) {
        this.MenuItemEliminar = MenuItemEliminar;
    }

    public JMenuItem getMenuItemInternacionales() {
        return MenuItemInternacionales;
    }

    public void setMenuItemInternacionales(JMenuItem MenuItemInternacionales) {
        this.MenuItemInternacionales = MenuItemInternacionales;
    }

    public JMenuItem getMenuItemModificar() {
        return MenuItemModificar;
    }

    public void setMenuItemModificar(JMenuItem MenuItemModificar) {
        this.MenuItemModificar = MenuItemModificar;
    }

    public JMenuItem getMenuItemNacionales() {
        return MenuItemNacionales;
    }

    public void setMenuItemNacionales(JMenuItem MenuItemNacionales) {
        this.MenuItemNacionales = MenuItemNacionales;
    }

    public JMenuItem getMenuItemTransOceanicos() {
        return MenuItemTransOceanicos;
    }

    public void setMenuItemTransOceanicos(JMenuItem MenuItemTransOceanicos) {
        this.MenuItemTransOceanicos = MenuItemTransOceanicos;
    }

    public JMenuBar getMenuPrincipal() {
        return MenuPrincipal;
    }

    public void setMenuPrincipal(JMenuBar MenuPrincipal) {
        this.MenuPrincipal = MenuPrincipal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu MenuConsulta;
    private javax.swing.JMenu MenuEditar;
    private javax.swing.JMenuItem MenuItemAgregar;
    private javax.swing.JMenuItem MenuItemEliminar;
    private javax.swing.JMenuItem MenuItemInternacionales;
    private javax.swing.JMenuItem MenuItemModificar;
    private javax.swing.JMenuItem MenuItemNacionales;
    private javax.swing.JMenuItem MenuItemTransOceanicos;
    private javax.swing.JMenuBar MenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
